// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/protobuf/post.proto

package postv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	protobuf "post_api/internal/common/genproto/post/api/protobuf"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PostServiceName is the fully-qualified name of the PostService service.
	PostServiceName = "post.PostService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PostServiceCreatePostProcedure is the fully-qualified name of the PostService's CreatePost RPC.
	PostServiceCreatePostProcedure = "/post.PostService/CreatePost"
	// PostServiceReadPostProcedure is the fully-qualified name of the PostService's ReadPost RPC.
	PostServiceReadPostProcedure = "/post.PostService/ReadPost"
	// PostServiceUpdatePostProcedure is the fully-qualified name of the PostService's UpdatePost RPC.
	PostServiceUpdatePostProcedure = "/post.PostService/UpdatePost"
	// PostServiceDeletePostProcedure is the fully-qualified name of the PostService's DeletePost RPC.
	PostServiceDeletePostProcedure = "/post.PostService/DeletePost"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	postServiceServiceDescriptor          = protobuf.File_api_protobuf_post_proto.Services().ByName("PostService")
	postServiceCreatePostMethodDescriptor = postServiceServiceDescriptor.Methods().ByName("CreatePost")
	postServiceReadPostMethodDescriptor   = postServiceServiceDescriptor.Methods().ByName("ReadPost")
	postServiceUpdatePostMethodDescriptor = postServiceServiceDescriptor.Methods().ByName("UpdatePost")
	postServiceDeletePostMethodDescriptor = postServiceServiceDescriptor.Methods().ByName("DeletePost")
)

// PostServiceClient is a client for the post.PostService service.
type PostServiceClient interface {
	CreatePost(context.Context, *connect.Request[protobuf.CreatePostRequest]) (*connect.Response[protobuf.CreatePostResponse], error)
	ReadPost(context.Context, *connect.Request[protobuf.ReadPostRequest]) (*connect.Response[protobuf.ReadPostResponse], error)
	UpdatePost(context.Context, *connect.Request[protobuf.UpdatePostRequest]) (*connect.Response[protobuf.UpdatePostResponse], error)
	DeletePost(context.Context, *connect.Request[protobuf.DeletePostRequest]) (*connect.Response[protobuf.DeletePostResponse], error)
}

// NewPostServiceClient constructs a client for the post.PostService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPostServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PostServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &postServiceClient{
		createPost: connect.NewClient[protobuf.CreatePostRequest, protobuf.CreatePostResponse](
			httpClient,
			baseURL+PostServiceCreatePostProcedure,
			connect.WithSchema(postServiceCreatePostMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		readPost: connect.NewClient[protobuf.ReadPostRequest, protobuf.ReadPostResponse](
			httpClient,
			baseURL+PostServiceReadPostProcedure,
			connect.WithSchema(postServiceReadPostMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updatePost: connect.NewClient[protobuf.UpdatePostRequest, protobuf.UpdatePostResponse](
			httpClient,
			baseURL+PostServiceUpdatePostProcedure,
			connect.WithSchema(postServiceUpdatePostMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		deletePost: connect.NewClient[protobuf.DeletePostRequest, protobuf.DeletePostResponse](
			httpClient,
			baseURL+PostServiceDeletePostProcedure,
			connect.WithSchema(postServiceDeletePostMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// postServiceClient implements PostServiceClient.
type postServiceClient struct {
	createPost *connect.Client[protobuf.CreatePostRequest, protobuf.CreatePostResponse]
	readPost   *connect.Client[protobuf.ReadPostRequest, protobuf.ReadPostResponse]
	updatePost *connect.Client[protobuf.UpdatePostRequest, protobuf.UpdatePostResponse]
	deletePost *connect.Client[protobuf.DeletePostRequest, protobuf.DeletePostResponse]
}

// CreatePost calls post.PostService.CreatePost.
func (c *postServiceClient) CreatePost(ctx context.Context, req *connect.Request[protobuf.CreatePostRequest]) (*connect.Response[protobuf.CreatePostResponse], error) {
	return c.createPost.CallUnary(ctx, req)
}

// ReadPost calls post.PostService.ReadPost.
func (c *postServiceClient) ReadPost(ctx context.Context, req *connect.Request[protobuf.ReadPostRequest]) (*connect.Response[protobuf.ReadPostResponse], error) {
	return c.readPost.CallUnary(ctx, req)
}

// UpdatePost calls post.PostService.UpdatePost.
func (c *postServiceClient) UpdatePost(ctx context.Context, req *connect.Request[protobuf.UpdatePostRequest]) (*connect.Response[protobuf.UpdatePostResponse], error) {
	return c.updatePost.CallUnary(ctx, req)
}

// DeletePost calls post.PostService.DeletePost.
func (c *postServiceClient) DeletePost(ctx context.Context, req *connect.Request[protobuf.DeletePostRequest]) (*connect.Response[protobuf.DeletePostResponse], error) {
	return c.deletePost.CallUnary(ctx, req)
}

// PostServiceHandler is an implementation of the post.PostService service.
type PostServiceHandler interface {
	CreatePost(context.Context, *connect.Request[protobuf.CreatePostRequest]) (*connect.Response[protobuf.CreatePostResponse], error)
	ReadPost(context.Context, *connect.Request[protobuf.ReadPostRequest]) (*connect.Response[protobuf.ReadPostResponse], error)
	UpdatePost(context.Context, *connect.Request[protobuf.UpdatePostRequest]) (*connect.Response[protobuf.UpdatePostResponse], error)
	DeletePost(context.Context, *connect.Request[protobuf.DeletePostRequest]) (*connect.Response[protobuf.DeletePostResponse], error)
}

// NewPostServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPostServiceHandler(svc PostServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	postServiceCreatePostHandler := connect.NewUnaryHandler(
		PostServiceCreatePostProcedure,
		svc.CreatePost,
		connect.WithSchema(postServiceCreatePostMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	postServiceReadPostHandler := connect.NewUnaryHandler(
		PostServiceReadPostProcedure,
		svc.ReadPost,
		connect.WithSchema(postServiceReadPostMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	postServiceUpdatePostHandler := connect.NewUnaryHandler(
		PostServiceUpdatePostProcedure,
		svc.UpdatePost,
		connect.WithSchema(postServiceUpdatePostMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	postServiceDeletePostHandler := connect.NewUnaryHandler(
		PostServiceDeletePostProcedure,
		svc.DeletePost,
		connect.WithSchema(postServiceDeletePostMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/post.PostService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PostServiceCreatePostProcedure:
			postServiceCreatePostHandler.ServeHTTP(w, r)
		case PostServiceReadPostProcedure:
			postServiceReadPostHandler.ServeHTTP(w, r)
		case PostServiceUpdatePostProcedure:
			postServiceUpdatePostHandler.ServeHTTP(w, r)
		case PostServiceDeletePostProcedure:
			postServiceDeletePostHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPostServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPostServiceHandler struct{}

func (UnimplementedPostServiceHandler) CreatePost(context.Context, *connect.Request[protobuf.CreatePostRequest]) (*connect.Response[protobuf.CreatePostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("post.PostService.CreatePost is not implemented"))
}

func (UnimplementedPostServiceHandler) ReadPost(context.Context, *connect.Request[protobuf.ReadPostRequest]) (*connect.Response[protobuf.ReadPostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("post.PostService.ReadPost is not implemented"))
}

func (UnimplementedPostServiceHandler) UpdatePost(context.Context, *connect.Request[protobuf.UpdatePostRequest]) (*connect.Response[protobuf.UpdatePostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("post.PostService.UpdatePost is not implemented"))
}

func (UnimplementedPostServiceHandler) DeletePost(context.Context, *connect.Request[protobuf.DeletePostRequest]) (*connect.Response[protobuf.DeletePostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("post.PostService.DeletePost is not implemented"))
}
